name: Figlet ASCII Art Workflow
on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Text to convert to ASCII art'
        required: true
        default: 'Hello World'
        type: string

jobs:
  generate-ascii:
    runs-on: schedin-arc-runner-scale-set
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: ls -l ${HOME}/_work/_temp/

      # - name: Sleep for development purposes
      #   run: sleep 3600

      - name: Generate ASCII Art
        uses: ./.github/actions/figlet-action
        id: figlet
        with:
          text: ${{ github.event.inputs.text }}
          
      - name: Display ASCII Art
        run: |
          echo "Generated ASCII Art:"
          cat << 'EOF'
          ${{ steps.figlet.outputs.ascii_art }}
          EOF