name: Release Container Images

on:
  release:
    types: [published]

env:
  REGISTRY: localhost:12345/simple-webapp

jobs:
  build-frontend:
    name: Build Web Frontend
    runs-on: self-hosted
    env:
      FRONTEND_IMAGE_NAME: counter-web
      FRONTEND_IMAGE_TAG: ${{ github.event.release.tag_name }}
    defaults:
      run:
        working-directory: ./web

    steps:
      - uses: actions/checkout@v3
          
      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Build Docker image
        run: podman build -t ${{ env.FRONTEND_IMAGE_NAME }}:${{ env.FRONTEND_IMAGE_TAG }} .

      - name: Push container  to registry
        run: skopeo copy containers-storage:localhost/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.FRONTEND_IMAGE_TAG }} docker://${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.FRONTEND_IMAGE_TAG }}

  build-backend:
    name: Build Kotlin Backend
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - uses: actions/checkout@v3

      - name: Build everything
        run: ./build-and-package.sh ${{ github.event.release.tag_name }}
