name: Release Container Images

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build-frontend:
    name: Build Web Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - run: pwd
      - run: ls -la

      - name: Build everything
        run: ./build-and-package.sh

  build-backend:
    name: Build Kotlin Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
        
    steps:
      - uses: actions/checkout@v3
      

